### ISSUE TITLE
Is this Doctrine bundle compatible with ODM as well?

### ISSUE THREAD

**Issue by redox** [algolia/AlgoliaSearchBundle#3]
To be used with MongoDB for instance: http://doctrine-mongodb-odm.readthedocs.org/en/latest/

**Comment by websirnik** [comment]
Got around testing this just now.

It works fine on a single document.

One common use-case most people will have with mongo is embedded documents: http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/embedded-mapping.html

Currently this is not handled out of the box. In the current setup:

```php

use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Algolia\AlgoliaSearchSymfonyDoctrineBundle\Mapping\Annotation as Algolia;

/**
 * @MongoDB\Document
 */
class Post
{

    /**
     * @Algolia\Attribute
     * @MongoDB\String
     */
    protected $title;

    /**
     * @Algolia\Attribute
     * @MongoDB\EmbedMany(targetDocument="author")
     */
    protected $authors = array();

}

/**
 * @MongoDB\EmbeddedDocument
 */
class Author
{

    /**
     * @Algolia\Attribute
     * @MongoDB\String
     */
    protected $name;

}
```
At the moment, this results in two different indexes in Algolia -> Post & Author. 
Post has an empty Author property. And each time I update Post, it creates a new Author object in the Author index. 

Post index:
```json
{
  "title": "Test",
  "authors": {},
  "objectID": "xxx"
}
```
Author index:
```json
{
  "name": "John",
  "objectID": "xxx"
}
```

The expected behaviour -> have just Post index with an Author property, that would contain an array of Author objects.
Post index:
```json
{
  "title": "Test",
  "authors": [
   {
      "name": "John"
   },
   {
      "name": "Mike"
   }],
  "objectID": "xxx"
}

**Comment by websirnik** [comment]
The other issue I've uncovered while trying to overcome Embedded documents limitation. The method annotation runs just once in the following setup:

```php
/**
 * @MongoDB\Document
 */
class Post
{

    /**
     * @Algolia\Attribute
     * @MongoDB\String
     */
    protected $title;

    /**
     * @Algolia\Attribute
     */
    public function getAuthors()
    {
        $authors = [];
        foreach ($this->authors as $author) {
            array_push($authors, $author->getName());
        }
        return $authors;
    }
}

```
When the post gets updated with new `$title` or new `$authors`, the update for `$title` does get sent to Algolia, but update for `$authors` does not.

**Comment by redox** [comment]
@djfm can you help?

**Comment by djfm** [comment]
I hope so :) I'll check the issues in detail this week-end!

**Comment by djfm** [comment]
Hi, this is trickier than I thought.

The main problem I see is that Doctrine does not trigger an "update" event on the `Post` object when its `authors` are updated.
It only triggers an "update" event on the `Post` object when authors are added or removed.
 
So, if we keep the data for authors in the same index as posts, we will miss a lot of events, which is what you are reporting:

"When the post gets updated with new $title or new $authors, the update for $title does get sent to Algolia, but update for $authors does not."
 
This would not be an issue with the SQL ORM, because in a traditional One-To-Many relationship, the "Many" side would hold a reference to the "One" side and we could easily treat both sides of the relation as separate indices.
What I mean is, we would have a `Post` index with no reference to the authors, and an `Author` index with each entry having a reference (id) to its owning `Post`.

But in Doctrine/Mongo the Authors seem completely unaware of the fact that they're actually inside a Post. Or can I get a "Post" from an "Author" in some way?

So the best suggestion I have for now is unfortunately a workaround:

First, remove the indexing annotations from the `Authors` model to prevent them from be indexed in their own index (or add `@Algolia\Index(autoIndex=false)` to the class docblock)

Second, use a getter to store the authors in the format you want like you described:

```php
/**
 * @Algolia\Attribute
 */
public function getAuthors()
{
    $authors = [];
    foreach ($this->authors as $author) {
        array_push($authors, $author->getName());
    }
    return $authors;
}
```

And third, this is where it gets hacky:

Do not rely on auto-indexing, and use the ManualIndexer to force the indexing of `Post`s when you change one of their authors:

```php
$post->getAuthors()[0]->setName('Some Other Name');
$em->persist($post);
$em->flush();
$this->get('algolia.indexer')->getManualIndexer($em)->index($post);
```

Would this help?

**Comment by websirnik** [comment]
Thanks for having a look on this. One thing to make sure we are on the same page:

> The main problem I see is that Doctrine does not trigger an "update" event on the Post object when its authors are updated.

I not super familiar with Doctrine event system. But I thought if the `Author` document is **embedded** inside `Post` and I'm persisting the `$post`: `$em->persist($post);`, there are should be some sort of Update event. As I'm not working with `Author` per se, I'm manipulating `$post` with contains a complete `Author` object.

There are two different mappings in Doctrine ODM:
- [Reference Mapping](http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/reference-mapping.html)
- [Embedded Mapping](http://doctrine-mongodb-odm.readthedocs.org/en/latest/reference/embedded-mapping.html)

I'm interested in the Embedded mapping. Is this the one you've tested as well?

> But in Doctrine/Mongo the Authors seem completely unaware of the fact that they're actually inside a Post. Or can I get a "Post" from an "Author" in some way?

I guess the idea of Doctrine embedded documents is that they don't need to be aware of where are they embedded. However when they do get updated, the parent document knows that.

---
I'll try the workaround in a meantime

**Comment by djfm** [comment]
Yes that's the embedded mapping I have tested, I will try to make a simple test case to demonstrate what I mean.

Also to make sure we're on the same page, when you say:

> When the post gets updated with new $title or new $authors, the update for $title does get sent to Algolia, but update for $authors does not.

By `new $authors` do you mean you're adding authors or changing authors that were already there?

> I not super familiar with Doctrine event system. But I thought if the Author document is embedded inside Post and I'm persisting the $post: $em->persist($post);, there are should be some sort of Update event.

Here are the results of my findings, but I need to double check because I might be wrong:

Action|Events Triggered
--------|----------------------
add an author to a post, persist the post|insert event on author, update on post
remove an author from a post, persist the post|delete event on author, update on post
modify an existing author, persist the post|update event on author, nothing on post

The last case is the one which causes the problem: the update event on author is useless unless I can link it with the post, but I haven't found how to do so yet. We would need a `$author->getPost()` or equivalent.

If interested, the heart of the change detection stuff is in here: https://github.com/algolia/AlgoliaSearchBundle/blob/mongo/EventListener/AlgoliaSearchDoctrineDocumentEventSubscriber.php#L40

**Comment by aequasi** [comment]
Any update on this? I'd love to use this
