### ISSUE TITLE
Is it possible to index serialized entities rather then properties directly?

### ISSUE THREAD

**Issue by araines** [algolia/AlgoliaSearchBundle#59]
I couldn't find mention of it in the documentation, so I suspect the answer is "no" but I've also seen a few issues kicking around here talking about Serialization.

The particular use case I'm going for is something similar to how the FOSElasticaBundle can be configured, whereby we would pass our entities through the Serializer before it goes to Algolia.  This would be great because then we are using the same JSON representation in Algolia search results as what we would usually serve via our API, meaning no database interaction required and clients could even talk directly to Algolia with ease.

Thanks!

**Comment by rayrutjes** [comment]
Hi @araines , sorry about the delay here.

Indeed today everything is kinda strongly coupled together making your approach hard to implement.

We will make sure the next version correctly introduces the right abstractions so that everyone can use their own implementations in the different layers.

I'm closing this for now as it will be solved in a new major release.

**Comment by rayrutjes** [comment]
I flagged it with V3 label to be sure we don't miss anything.
